### ISSUE TITLE
Add uqfinal/wdinotf support inline

### ISSUE THREAD

**Issue by svict4** [UQComputingSociety/uqcs-hubot#27]
```uqcsbot <uqfinal|wdinotf|final> econ1010 100```

would spit out

```You need 38.46% to pass on the final```

@gricey432 has made http://uqfinal.com/json/ECON1010.json available

**Comment by svict4** [comment]
closed by 7bd5711cb38db6475a7ed95edfc75ebdeb2bd0fc

**Comment by gricey432** [comment]
Heads up the api endpoint and the format of the json files will be changing completely soon.
I'll open a new issue with a spec soon so the code can be updated before I drop the old one

**Comment by lewisjb** [comment]
Thanks @gricey432
