### ISSUE TITLE
Add chat history support

### ISSUE THREAD

**Issue by svict4** [UQComputingSociety/uqcs-hubot#35]
Would be nice

**Comment by wisebaldone** [comment]
Should follow an opt in approach and not an opt out per channel basis.

**Comment by JosephGarrone** [comment]
Also, should display a message every so often stating that if you type your
password it will auto asterisk it like so *******************. It even
works in git issues!

**Comment by lewisjb** [comment]
#64 implemented basics, should implement black/whitelist for channels
