### ISSUE TITLE
!commands - display list of commands bot knows

### ISSUE THREAD

**Issue by deedubwhy** [UQComputingSociety/uqcs-hubot#68]
A large number of the bots commands generally go unused until someone that does know the command says it in a channel.

Let a user type `!commands` into any chatroom and either say a list of available commands in the channel or pm it to the user to prevent spam.

Should highlight recently added or updated commands as 'new'.

**Comment by JosephGarrone** [comment]
Closed #68. @day should be studying.

**Comment by TRManderson** [comment]
This is what !help does
